version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src:/opt/app/src
      - cargo-cache:/usr/local/cargo/registry
    env_file:
      - ./backend/.env
  db:
    image: postgres
    container_name: pointbreak-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  cargo-cache:
  postgres_volume:
