FROM rust:latest

RUN <<EOF
  apt-get update 
  apt-get install -y libssl-dev ca-certificates 
  rm -rf /var/lib/apt/lists/*
EOF

# 環境変数の設定
ENV APP_NAME pointbreak
ENV APP_ROOT /opt/app
WORKDIR $APP_ROOT

# 依存関係のインストールをソースコードのコピー前に実行することにより
# ソースコードの変更だけの場合実行しないようにする。
COPY ./Cargo.toml ./Cargo.lock ./

# ダミーソースファイルを作成して依存関係をプリコンパイル
RUN <<EOF
  mkdir src
  echo "fn main() {}" > src/main.rs
  echo "pub fn lib_dummy() {}" > src/lib.rs
  cargo build --release
  rm -rf ./src
EOF

# 実際のソースコードをマウント
VOLUME ["$APP_ROOT/src"]

RUN cargo install cargo-watch
#CMD ["cargo", "watch", "-x", "run"]
CMD ["cargo", "run"]
