test-create-session:
	curl -s -H 'Content-Type: application/json' -d '{"client_id":"foo","client_secret":"bar"}' https://nps7ce8bkw.ap-northeast-1.awsapprunner.com/user/session

test-auth:
	curl -s -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiQGIuY29tIiwiY29tcGFueSI6IkFDTUUiLCJleHAiOjIwMDAwMDAwMDB9.ULPZ0NLBq9tfHroRgxJJeEYCy0tguZrEwix3fo-2dFc' https://nps7ce8bkw.ap-northeast-1.awsapprunner.com/user/dashboard
